services:

  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  airflow-init:
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@airflow-postgres:5432/${POSTGRES_DB}
    build:
      context: .
      dockerfile: docker/Dockerfile.airflow
    depends_on:
      - postgres
    env_file:
      - .env
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db init &&
      airflow users create
      --username ${AIRFLOW_ADMIN_USER}
      --password ${AIRFLOW_ADMIN_PASSWORD}
      --firstname admin
      --lastname user
      --role Admin
      --email admin@example.com
      "

  airflow-webserver:
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@airflow-postgres:5432/${POSTGRES_DB}
    build:
      context: .
      dockerfile: docker/Dockerfile.airflow
    container_name: airflow-webserver
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./data:/opt/airflow/data
    restart: always

  airflow-scheduler:
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@airflow-postgres:5432/${POSTGRES_DB}
    build:
      context: .
      dockerfile: docker/Dockerfile.airflow
    container_name: airflow-scheduler
    depends_on:
      - postgres
    env_file:
      - .env
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./data:/opt/airflow/data
    restart: always

volumes:
  postgres-db-volume:
